# Generated by Django 6.0.2 on 2026-03-12 23:31

import django.db.models.deletion
import reclamos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(3, 'Alta'), (2, 'Media'), (1, 'Baja')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reclamos.estadoreclamo')),
                ('id_contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamos.contribuyente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_ult_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_modificados', to=settings.AUTH_USER_MODEL)),
                ('tipo_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reclamos.tiporeclamo')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=reclamos.models.ReclamoFoto.ruta_foto_reclamo)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='reclamos.reclamo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('prioridad_anterior', models.IntegerField(blank=True, null=True)),
                ('prioridad_nueva', models.IntegerField(blank=True, null=True)),
                ('titulo_anterior', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo_nuevo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_anterior', models.TextField(blank=True, null=True)),
                ('descripcion_nueva', models.TextField(blank=True, null=True)),
                ('vecino_anterior', models.IntegerField(blank=True, null=True)),
                ('vecino_nuevo', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_anterior', to='reclamos.estadoreclamo')),
                ('estado_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_nuevo', to='reclamos.estadoreclamo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reclamos.reclamo')),
                ('tipo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_anterior', to='reclamos.tiporeclamo')),
                ('tipo_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_nuevo', to='reclamos.tiporeclamo')),
            ],
        ),
    ]
