# Generated by Django 3.2 on 2026-03-19 18:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0002_fix_fk_prod'),  # <- corregido
    ]

    operations = [
        # acá van tus operaciones de arreglar foreign keys
    ]
