# Generated by Django 6.0.3 on 2026-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0004_alter_reclamo_usuario_ult_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialreclamo',
            name='descripcion_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialreclamo',
            name='descripcion_nueva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialreclamo',
            name='prioridad_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialreclamo',
            name='prioridad_nueva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialreclamo',
            name='titulo_anterior',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historialreclamo',
            name='titulo_nuevo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historialreclamo',
            name='vecino_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialreclamo',
            name='vecino_nuevo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
