# Generated by Django 3.2 on 2026-03-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0005_fix_fk_reclamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='id_contribuyente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclamos.contribuyente'),
        ),
    ]
