# Generated by Django 3.2 on 2026-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0006_auto_20260319_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='entre_calle_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='entre_calle_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
