# Generated by Django 3.2 on 2026-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0007_auto_20260415_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='apellido_contacto',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='dni_ingresado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='nombres_contacto',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
