# Generated by Django 3.2 on 2026-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0008_auto_20260415_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
